name: Gateway Update

on:
  pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'main' || 'test' }}

    steps:
      - uses: actions/checkout@v4
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.DEPLOY_WID }}'
          service_account: '${{ secrets.DEPLOY_SERVICE_ACCOUNT }}'
      - name: Prepare API config
        env:
          GRPC_DASHBOARDS_PUBLIC_HOST: ${{ secrets.GRPC_DASHBOARDS_PUBLIC_HOST }}
        run: |- 
          variable_escaped='${{ '\${{ *secrets.GRPC_DASHBOARDS_PUBLIC_HOST *}}' }}'
          sed -i -e  "s@$variable_escaped@$GRPC_DASHBOARDS_PUBLIC_HOST@g" public_api_config.yml
          cp -r proto deploy_api
          make
          cp gen/go/dashboards/api_descriptor.pb deploy_api/api_descriptor.pb