name: Gateway Update

on:
  pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - uses: actions/checkout@v4

      - name: Print envs
        env:
          GRPC_DASHBOARDS_PUBLIC_HOST: ${{ secrets.GRPC_DASHBOARDS_PUBLIC_HOST }}
        run: |- 
          value_escaped="${GRPC_DASHBOARDS_PUBLIC_HOST//\//\\\/}"
          value_escaped="${value_escaped//\./\\\.}"
          variable_escaped='${{ '\${{ *env.GRPC_DASHBOARDS_PUBLIC_HOST *}}' }}'
          command="s/$variable_escaped/$value_escaped/g"
          echo $command
          echo "${#command}"
          sed -i '' -e  $command public_api_config.yml
          cat public_api_config.yml
