name: Gateway Update

on:
  pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - uses: actions/checkout@v4

      - name: Print envs
        run: |- 
          echo "${{ secrets.GRPC_DASHBOARDS_PUBLIC_HOST }}"
          echo "${{ secrets.GRPC_DASHBOARDS_PUBLIC_PORT }}"
          env
