name: Gateway Update

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'main' || 'test' }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.*'
      - name: Prepare API config
        env:
          GRPC_DASHBOARDS_PUBLIC_HOST: ${{ secrets.GRPC_DASHBOARDS_PUBLIC_HOST }}
        run: |- 
          variable_escaped='${{ '\${{ *secrets.GRPC_DASHBOARDS_PUBLIC_HOST *}}' }}'
          sed -i -e  "s@$variable_escaped@$GRPC_DASHBOARDS_PUBLIC_HOST@g" public_api_config.yml
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
          export PATH="$PATH:$(go env GOPATH)/bin"
          cd proto
          ls 
          make grpc-with-descriptors-github
          ls 
          cd ..
          ls
          cp -r proto deploy_api
          cp gen/go/dashboards/api_descriptor.pb deploy_api/api_descriptor.pb
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.DEPLOY_WID }}'
          service_account: '${{ secrets.DEPLOY_SERVICE_ACCOUNT }}'
      - name: Update API Gateway
        run: |-
          cd deploy_api
          gcloud api-gateway api-configs create dashboards-public-config-${{ github.sha }} \
            --api=dashboards-public-api --project=${{ secrets.GCP_PROJECT }} \
            --grpc-files=api_descriptor.pb,public_api_config.yaml
          gcloud api-gateway gateways update dashboards-public-gateway \
            --api=dashboards-public-api --api-config=dashboards-public-config-${{ github.sha }}
