name: Gateway Update

on:
  pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - uses: actions/checkout@v4

      - name: Print envs
        env:
          GRPC_DASHBOARDS_PUBLIC_HOST: ${{ vars.GRPC_DASHBOARDS_PUBLIC_HOST }}
        run: |- 
          variable_escaped='${{ '\${{ *vars.GRPC_DASHBOARDS_PUBLIC_HOST *}}' }}'
          sed -i -e  "s@$variable_escaped@$GRPC_DASHBOARDS_PUBLIC_HOST@g" public_api_config.yml
          cat public_api_config.yml