name: Gateway Update

on:
  pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Print envs
        uses: actions/checkout@v4
        env:
          GRPC_DASHBOARDS_PUBLIC_HOST: ${{ secrets.GRPC_DASHBOARDS_PUBLIC_HOST }}
        run: |- 
          variable_escaped='${{ '\${{ *env.GRPC_DASHBOARDS_PUBLIC_HOST *}}' }}'
          ls
          sed -i '' -e  "s@$variable_escaped@$GRPC_DASHBOARDS_PUBLIC_HOST@g" public_api_config.yml
          ls
          cat public_api_config.yml
