name: Gateway Update

on:
  pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'main' || 'test' }}

    steps:
      - uses: actions/checkout@v4
      - name: Docker Auth
          id: docker-auth
          uses: 'docker/login-action@v3'
          with:
            username: 'oauth2accesstoken'
            password: '${{ steps.auth.outputs.access_token }}'
            registry: '${{ secrets.ARTIFACT_REGISTRY }}' 
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.*'
      - name: Prepare API config
        env:
          GRPC_DASHBOARDS_PUBLIC_HOST: ${{ secrets.GRPC_DASHBOARDS_PUBLIC_HOST }}
        run: |- 
          variable_escaped='${{ '\${{ *secrets.GRPC_DASHBOARDS_PUBLIC_HOST *}}' }}'
          sed -i -e  "s@$variable_escaped@$GRPC_DASHBOARDS_PUBLIC_HOST@g" public_api_config.yml
          cp -r proto deploy_api
          make
          cp gen/go/dashboards/api_descriptor.pb deploy_api/api_descriptor.pb